# Generated by Django 5.2.6 on 2025-09-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='profile_qrcodes/', verbose_name='QR-код профілю')),
                ('background', models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/', verbose_name='Фонове зоображення')),
                ('background_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Колір фону')),
                ('button_style', models.CharField(choices=[('rounded', 'Закруглені'), ('square', 'Прямі'), ('pill', 'Таблетка')], default='rounded', max_length=50, verbose_name='Стиль кнопок')),
                ('text_color', models.CharField(default='#000000', max_length=20, verbose_name='Колір тексту')),
                ('slug', models.SlugField(help_text='Наприклад: yourname, буде доступно за /u/yourname/', unique=True, verbose_name="URL-ім'я")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('url', models.URLField(verbose_name='Посилання')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_links', to='profiles.publicprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва соцмережі')),
                ('url', models.URLField(verbose_name='Посилання')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profiles.publicprofile')),
            ],
            options={
                'unique_together': {('profile', 'name')},
            },
        ),
    ]
