# Generated by Django 5.2.6 on 2025-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Безкоштовний'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20, verbose_name='Тариф'),
        ),
    ]
