# Generated by Django 5.2.6 on 2025-09-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_sociallink_unique_together_publicprofile_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('utm_source', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='profiles.publicprofile')),
            ],
        ),
    ]
