# Generated by Django 5.2.6 on 2025-09-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profileclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='is_active_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
